apiVersion: launcher.fabric8.io/v1alpha2
kind: Launcher
metadata:
  name: launcher
spec:

####### OpenShift Configuration
  openshift:
    consoleUrl: https://192.168.42.39:8443/console

####### OAuth Configuration
  oauth:
    enabled: true

  git:
    - id: GitHub
      clientId: "12"
      clientSecret: "12"
